export const places = [
 {id:'research',title:'Research centre',short:'Research & communication',position:[-15,-5],anchor:[-15,9,-12],colour:'#b5674e',period:'2021–2024 · Energy and Resources Institute',tag:'A place for people, ideas and research',intro:'My university journey began in research administration and grew into communications and coordination. Choose whichever part you would like to look into.',stories:[
  {title:'Helping research come together',label:'Research administration',copy:'I organised meetings and supported research committees, managed records, purchasing and travel, and worked with researchers, professional staff and partners. Understanding how the institute operated helped me see where I could contribute.',links:[]},
  {title:'Making the work easier to share',label:'Communication',copy:'My work grew to include the communication plan, website structure, newsletters and institute content. I also coordinated the institute’s annual reports and worked with the design team on its brochure.',links:[['Explore the ERI website','https://www.cdu.edu.au/eri']]},
  {title:'Creating places for exchange',label:'Events & connection',copy:'I coordinated industry training, networking events and the ERI Seminar Series. For the Australian Combustion Symposium 2023, my work included promotion, registration, logistics and coordination.',links:[['Australian Combustion Symposium','https://anz-combustioninstitute.org/ACS2023/index.php'],['ERI Seminar Series','https://www.cdu.edu.au/eri/connect/eri-seminar-series']]},
  {title:'Supporting Kiran’s research journey',label:'Kiran’s journey',period:'2026 · A personal connection to research',copy:'Alongside my own university career, I have supported my husband Kiran’s research journey, from organic solar cells to quantum computing. It is a personal connection to research that continues as we build our life in Melbourne.',links:[],chapters:[
   {label:'Organic solar cells',copy:'Kiran’s earlier research explored quantum dot organic solar cells. I have been alongside him as his research interests developed and new questions led him towards quantum computing.'},
   {label:'Quantum computing',copy:'In 2026, Kiran began his second PhD at Deakin University. I moved to Melbourne to support this next chapter, while continuing my own career in communication, coordination and supporting people in university settings.'}
  ]}
 ]},
 {id:'students',title:'Student hub',short:'Groups, leadership & belonging',position:[15,-5],anchor:[15,8.4,-12],colour:'#368782',period:'2024–2026 · Student engagement',tag:'Different groups. A shared university.',intro:'Each student group brought its own purpose and community. My role brought together relationships, leadership development and the systems that supported their work.',stories:[
  {title:'Getting to know the people',label:'Mentoring',copy:'I supported more than 25 student committees, listening to what each group represented and helping elected members understand their responsibilities. Building trust mattered when committees needed guidance or faced a difficult situation.',links:[]},
  {title:'Giving the next committee a starting point',label:'Program building',copy:'I strengthened the affiliation process and developed guidance, templates, training and a Student Groups Handbook. Shared email, Teams and SharePoint helped committees keep information and knowledge through transitions.',links:[['Explore the program roadmap','roadmap/']]},
  {title:'Learning through participation',label:'Leadership development',copy:'I organised leadership training, developed its content, presented key concepts and designed collaborative activities. My leadership styles quiz offers another way to reflect on communication, decisions and working with others.',links:[['Try the leadership quiz','https://gopika2093.github.io/leadership-quiz/']]}
 ]},
 {id:'carnival',title:'Carnival courtyard',short:'Ideas, events & teamwork',position:[-15,16],anchor:[-15,5.5,10],colour:'#bd7451',period:'2024–2026 · Campus activation',tag:'An idea that brought people together',intro:'Student Carnival grew from a networking event into a recurring event brand. It gave student groups a shared space to connect with one another and the wider student community.',stories:[
  {title:'One identity, different experiences',label:'The Carnival idea',copy:'I developed a consistent identity that made Student Carnival easier to recognise, communicate and promote. The Opening, Dry Season and Red Carpet editions each offered a different experience.',links:[]},
  {title:'Helping a team take shape',label:'The event team',copy:'My work with student casuals began with recruitment and continued as they became part of the event team. Through training and mentoring, I helped them understand their roles, then supported them as they put that preparation into practice during larger campus events.',links:[]},
  {title:'Thinking about the experience',label:'Planning & delivery',copy:'Preparation involved considering the audience, the setting and the people delivering the event. Logistics, communication, risk and team coordination came together to support an experience where student groups and visitors could connect.',links:[]}
 ]},
 {id:'cafe',title:'Campus café',short:'Coffee & a conversation',position:[15,16],anchor:[16,6.4,10],colour:'#aa813d',period:'Melbourne · The journey continues',tag:'There is always more to talk about.',intro:'The questions, conversations and small decisions behind my work cannot all fit on a webpage. If something here interests you, I would be glad to continue the conversation.',image:{src:'assets/cafe-conversation.png',alt:'Two coffees and an open journal beside a café window overlooking a university streetscape. The journal reads “Listen. Learn. Contribute.” and “Key learnings from the conversation:”.'},stories:[
  {title:'A conversation can be a beginning',label:'Let’s connect',copy:'I recently moved to Melbourne after almost five years at Charles Darwin University. I would welcome the opportunity to meet people, hear different perspectives and explore where my experience could be useful.',links:[['Start a conversation','mailto:gopikagopan2093@gmail.com'],['Connect on LinkedIn','https://www.linkedin.com/in/gopika-gopan-prema-14a20421b/']]}
 ]}
];
